version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run:
          command: |
          pip install wheel
      - run:
          command: |
            python setup.py sdist bdist_wheel
      - run:
          command: |
            pypi-private -v publish launchpotato-extralibs $CIRCLE_TAG