version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run:
          command: |
            pip install wheel pypiprivate
      - run:
          command: |
            python setup.py sdist bdist_wheel
      - run:
          command: |
            if [ "$CIRCLE_TAG" != "" ] ; then echo pypi-private -v publish launchpotato-extralibs $CIRCLE_TAG ; fi