version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run:
          command: |
            pip install wheel pypiprivate
      - run:
          command: |
            python setup.py sdist bdist_wheel
      - run:
          command: |
            echo $CIRCLE_TAG
            if [ "$CIRCLE_TAG" != "" ] ; then pypi-private -c .pypi-private.cfg -v publish launchpotato-extralibs $CIRCLE_TAG ; fi


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/