version: 2.1
jobs:
  checkout_code_and_test:
    working_directory: ~/app
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - save_cache:
          key: repo-{{.Environment.CIRCLE_SHA1}}
          paths:
            - ~/app
      - run:
          command: |
            python setup.py sdist bdist_wheel
      - run:
          command: |
            pypi-private -v publish launchpotato-extralibs $CIRCLE_TAG